include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    public_member_api_docs: false
    lines_longer_than_80_chars: 120
