workflows:
  WEB:
    name: Build Web
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6
      groups:
        - gemini
        - firebase

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: "Create env.json file"
        script: |
          bash scripts/frontend/create_env_file.sh --firebase-app-id=$FIREBASE_APP_ID --firebase-api-key=$FIREBASE_API_KEY --firebase-auth-domain=$FIREBASE_AUTH_DOMAIN --firebase-project-id=$FIREBASE_PROJECT_ID --firebase-store-bucket=$FIREBASE_STORE_BUCKET --firebase-messaging-sender-id=$FIREBASE_MESSAGING_SENDER_ID --gemini-api-key=$GEMINI_API_KEY;
      - name: "Enable web"
        script: |
          flutter config --enable-web;
      - name: "Build web"
        script: |
          cd frontend;
          flutter build web --release --dart-define-from-file=env.json;
          cd build/web;
          7z a -r ../web.zip ./*

    artifacts:
      - frontend/build/*.zip
