name: Web App

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/**

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Build Web
        working-directory: frontend
        run: |
          cd scripts
          bash create_env_file.sh --firebase-app-id=$FIREBASE_APP_ID --firebase-api-key=$FIREBASE_API_KEY --firebase-auth-domain=$FIREBASE_AUTH_DOMAIN --firebase-project-id=$FIREBASE_PROJECT_ID --firebase-store-bucket=$FIREBASE_STORE_BUCKET --firebase-messaging-sender-id=$FIREBASE_MESSAGING_SENDER_ID --gemini-api-key=$GEMINI_API_KEY;
          cd ..
          flutter build web --release --dart-define-from-file=env.json

      - name: Deploy
        working-directory: frontend/scripts
        run: bash send_code_builded_to_git.sh
#
